### ISSUE TITLE
Extract the business logic into a separate npm package

### ISSUE THREAD

**Issue by frol** [near/account-lookup#15]
We currently have a copy-paste implementation with some extra features on NEAR Wallet side and we plan to also integrate lockup viewing into NEAR Explorer.

@shelegdmitriy As per our discussion, please, extract the main logic into a separate git repo and make npm package out of it. Check out Wallet code to see what data do they need, so this new package can provide it.

**Comment by shelegdmitriy** [comment]
Here is a link to npm package https://www.npmjs.com/package/near-lockup-helper, so I guess we can close this issue
