### ISSUE TITLE
The data is wrong if we use custom block_height

### ISSUE THREAD

**Issue by telezhnaya** [near/account-lookup#21]
Story
we have an account https://explorer.near.org/accounts/opgran01.near
we checked the info for this account at the moment 31 dec 2020 (block_height 26490580)
the tool told us this account had 40 tokens as the owner and 35 tokens on the lockup
but in reality, the lockup had huge amount of money and we have the TX about it
https://explorer.near.org/transactions/3db8TpxEu1kSB4v4mPRBCqHsBBna8Zfq2Jkvf67A4CVs
These tokens were moved later, but only at Jan 12, 2021, so it shouldn't be shown at the moment Dec 31 2020.
https://explorer.near.org/transactions/9bw5bvmDGG2CkqgKhC51Yz2rLPLFCwSJXSWgGgsCYvZe#7hyM3yPVs1X8SJmhpYHj2ADmdtuM1rG4etUboH3adDd2

I was using this branch to debug it on the historical data https://github.com/near/account-lookup/tree/temp_foundation_liquid_amount
I tried to create the hotfix for my solution https://github.com/near/account-lookup/pull/20, but it should be much more complex.
I've also found some bugs there. These places are taking the information about the latest block, not about the desired one.
https://github.com/near/account-lookup/blob/temp_foundation_liquid_amount/script.js#L120
https://github.com/near/account-lookup/blob/temp_foundation_liquid_amount/script.js#L299
All viewFunction calls do the same
https://github.com/near/account-lookup/blob/temp_foundation_liquid_amount/script.js#L166

It's better to start from the beginning and create the solution where it's possible to enter the optional desired block_height at the main page. 

Our final goal is to have the ability to set up the desired moment and see:
- account balance
- account staking info
- lockup balance
- lockup locked balance
- lockup staking info

**Comment by frol** [comment]
It seems that we expect that the tokens (1_900_000 NEAR) should be completely locked before Oct 25th, 2020, and completely unlocked after that time before they were withdrawn on Jan 12th, 2021.

**Comment by telezhnaya** [comment]
You may also see the issue that `liquid + locked tokens = total - one_of(35, 3.5)`
The reason for that is that we block this sum for the storage needs. The sum was changed in one of the lockup contract versions, that's why you see 2 possible constants there.
 I assume we should also treat this number as locked and add it to other locked tokens.

**Comment by frol** [comment]
> I assume we should also treat this number as locked and add it to other locked tokens.

Oh, I don't want to dive into that rabbit hole and overload the "locked" term even more 🥲

**Comment by shelegdmitriy** [comment]
@frol I just published the new version of [near-lockup-helper-js](https://www.npmjs.com/package/near-lockup-helper) so you can go on with this task

**Comment by frol** [comment]
Resolved in https://github.com/near/near-lockup-helper-js/pull/4 and https://github.com/near/near-lockup-helper-js/pull/9 and also re-implemented the script that we used to output CSV: https://github.com/near/account-lookup-script
